#!/bin/bash
# Compile
arduino-cli compile --fqbn esp32:esp32:esp32 arduino/ --verbose -e #--build-properties build.partitions=huge_app,upload.maximum_size=3000000

# Upload
arduino-cli upload -p /dev/ttyUSB0 --fqbn esp32:esp32:esp32 arduino/

# Monitor
#python3 sendBytes.py -r defaultInput
