enum SCRATCH_opcode opcodes : uint8_t {
    INNER_PARTITION_BEGINLOOPCONTROL,
    INNER_LOOPINIT,
    INNER_LOOPINCREMENT,
    INNER_JUMPIFREPEATDONE,

    EVENT_WHENFLAGCLICKED,
    MOTION_MOVESTEPS,
    MOTION_TURNRIGHT,
    MOTION_GOTO,
    MOTION_GOTO_MENU,
    MOTION_GOTOXY,
    MOTION_GLIDETO,
    MOTION_GLIDETO_MENU,
    MOTION_GLIDESECSTOXY,
    MOTION_POINTINDIRECTION,
    MOTION_POINTTOWARDS,
    MOTION_POINTTOWARDS_MENU,
    MOTION_CHANGEXBY,
    MOTION_SETX,
    MOTION_CHANGEYBY,
    MOTION_SETY,
    MOTION_IFONEDGEBOUNCE,
    MOTION_SETROTATIONSTYLE,
    MOTION_XPOSITION,
    MOTION_YPOSITION,
    MOTION_DIRECTION,
    LOOKS_SAYFORSECS,
    LOOKS_SAY,
    LOOKS_THINKFORSECS,
    LOOKS_THINK,
    LOOKS_SWITCHCOSTUMETO,
    LOOKS_COSTUME,
    LOOKS_NEXTCOSTUME,
    LOOKS_SWITCHBACKDROPTO,
    LOOKS_BACKDROPS,
    LOOKS_NEXTBACKDROP,
    LOOKS_CHANGESIZEBY,
    LOOKS_SETSIZETO,
    LOOKS_CHANGEEFFECTBY,
    LOOKS_SETEFFECTTO,
    LOOKS_CLEARGRAPHICEFFECTS,
    LOOKS_SHOW,
    LOOKS_HIDE,
    LOOKS_GOTOFRONTBACK,
    LOOKS_GOFORWARDBACKWARDLAYERS,
    LOOKS_COSTUMENUMBERNAME,
    LOOKS_BACKDROPNUMBERNAME,
    LOOKS_SIZE,
    SOUND_PLAYUNTILDONE,
    SOUND_SOUNDS_MENU,
    SOUND_PLAY,
    SOUND_STOPALLSOUNDS,
    SOUND_CHANGEEFFECTBY,
    SOUND_SETEFFECTTO,
    SOUND_CLEAREFFECTS,
    SOUND_CHANGEVOLUMEBY,
    SOUND_SETVOLUMETO,
    SOUND_VOLUME,
    EVENT_WHENKEYPRESSED,
    EVENT_WHENTHISSPRITECLICKED,
    EVENT_WHENBACKDROPSWITCHESTO,
    EVENT_WHENGREATERTHAN,
    EVENT_WHENBROADCASTRECEIVED,
    EVENT_BROADCAST,
    EVENT_BROADCASTANDWAIT,
    CONTROL_WAIT,
    CONTROL_REPEAT,
    CONTROL_FOREVER,
    CONTROL_IF,
    CONTROL_IF_ELSE,
    CONTROL_WAIT_UNTIL,
    CONTROL_REPEAT_UNTIL,
    CONTROL_STOP,
    CONTROL_START_AS_CLONE,
    CONTROL_CREATE_CLONE_OF,
    CONTROL_CREATE_CLONE_OF_MENU,
    CONTROL_DELETE_THIS_CLONE,
    SENSING_TOUCHINGOBJECT,
    SENSING_TOUCHINGOBJECTMENU,
    SENSING_TOUCHINGCOLOR,
    SENSING_COLORISTOUCHINGCOLOR,
    SENSING_DISTANCETO,
    SENSING_DISTANCETOMENU,
    SENSING_ASKANDWAIT,
    SENSING_ANSWER,
    SENSING_KEYPRESSED,
    SENSING_KEYOPTIONS,
    SENSING_MOUSEDOWN,
    SENSING_MOUSEX,
    SENSING_MOUSEY,
    SENSING_SETDRAGMODE,
    SENSING_LOUDNESS,
    SENSING_TIMER,
    SENSING_RESETTIMER,
    SENSING_OF,
    SENSING_OF_OBJECT_MENU,
    SENSING_CURRENT,
    SENSING_DAYSSINCE2000,
    SENSING_USERNAME,
    OPERATOR_ADD,
    OPERATOR_SUBTRACT,
    OPERATOR_MULTIPLY,
    OPERATOR_DIVIDE,
    OPERATOR_RANDOM,
    OPERATOR_GT,
    OPERATOR_LT,
    OPERATOR_EQUALS,
    OPERATOR_AND,
    OPERATOR_OR,
    OPERATOR_NOT,
    OPERATOR_JOIN,
    OPERATOR_LETTER_OF,
    OPERATOR_LENGTH,
    OPERATOR_CONTAINS,
    OPERATOR_MOD,
    OPERATOR_ROUND,
    OPERATOR_MATHOP,
    DATA_SETVARIABLETO,
    DATA_CHANGEVARIABLEBY,
    DATA_SHOWVARIABLE,
    DATA_HIDEVARIABLE,
};

enum SCRATCH_opcode : uint8_t {
    CONTROL_STOP,
    SCRATCH_PARTITION_BEGINLOOPCONTROL, // Semantic partition.

    // Loop opcodes. 

    INNER_LOOPINIT,        // Push loop counter to loop stack
    INNER_LOOPINCREMENT,   // Increment the top of stack loop counter
    INNER_JUMPIFREPEATDONE,// Jump if the top of the loop stack has reached a value   @field loop value @field jump location

    INNER_PARTITION_BEGINEXPRESSIONS, // Semantic partition.

    // Expression opcodes. May pop from the stack; always push to the stack.

    SENSING_TOUCHINGOBJECT,         // 
    SENSING_TOUCHINGOBJECTMENU,     // IMPLEMENTED VIA FETCHPOSITION
    SENSING_TOUCHINGCOLOR,          // UNUSED
    SENSING_COLORISTOUCHINGCOLOR,   // UNUSED
    SENSING_DISTANCETO,
    SENSING_DISTANCETOMENU,         // IMPLEMENTED VIA FETCHPOSITION
    SENSING_ASKANDWAIT,
    SENSING_ANSWER,                 // RETURNS EMPTY STRING
    SENSING_KEYPRESSED,
    SENSING_KEYOPTIONS,             // UNUSED
    SENSING_MOUSEDOWN,
    SENSING_MOUSEX,
    SENSING_MOUSEY,
    SENSING_SETDRAGMODE,            // UNUSED
    SENSING_LOUDNESS,               // UNUSED
    SENSING_TIMER,
    SENSING_RESETTIMER,
    SENSING_OF,
    SENSING_OF_OBJECT_MENU,         // IMPLEMENTED VIA SPRITE INDICES
    SENSING_CURRENT,                // ALWAYS RETURNS AS IF JAN 1ST 2025 00:00
    SENSING_DAYSSINCE2000,          // RETURNS FOR JAN 1ST 2025
    SENSING_USERNAME,

    INNER_FETCHINPUT,               

    INNER_FETCHVAR,                 
    INNER_PUSH,                     

    OPERATOR_ADD,
    OPERATOR_SUBTRACT,
    OPERATOR_MULTIPLY,
    OPERATOR_DIVIDE,
    OPERATOR_RANDOM,
    OPERATOR_GT,
    OPERATOR_LT,
    OPERATOR_EQUALS,
    OPERATOR_GE,
    OPERATOR_AND,
    OPERATOR_OR,
    OPERATOR_NOT,
    OPERATOR_JOIN,
    OPERATOR_LETTER_OF,
    OPERATOR_LENGTH,
    OPERATOR_CONTAINS,
    OPERATOR_MOD,
    OPERATOR_ROUND,
    OPERATOR_MATHOP,

    INNER_DEBUGEXPRESSION,

    INNER_PARTITION_BEGINSTATEMENTS, // Semantic partition.
    // Only statement opcodes need to mind their return value. Still, for predictability, expression opcodes should return
    // SCRATCH_continue.

    // Statement opcodes. Statements always leave the stack empty, unless there has been an error in compilation or implementation.
    DATA_SETVARIABLETO,          // Set a variable                                           @field variable index @input data
    DATA_CHANGEVARIABLEBY,          // increment a variable                                     @field variable index @input amount
    DATA_SHOWVARIABLE,
    DATA_HIDEVARIABLE,

    INNER_LOOPJUMP,        // Signal a loop iteration to interpreter                   @field jump destination
    CONTROL_CREATE_CLONE_OF,           // Treat cloning as a privileged primitive operation        @input sprite index
    CONTROL_WAIT,
    CONTROL_REPEAT,
    CONTROL_FOREVER,
    CONTROL_IF,
    CONTROL_IF_ELSE,
    CONTROL_WAIT_UNTIL,
    CONTROL_REPEAT_UNTIL,
    CONTROL_STOP,
    CONTROL_CREATE_CLONE_OF_MENU,
    CONTROL_DELETE_THIS_CLONE,          // Delete a sprite
    CONTROL_WAIT,
    INNER_JUMPIF,          // Jump if top of stack is truthy                           @input evaluand @field jump destination
    INNER_JUMPIFNOT,       // Jump if top of stack is not truthy      @input evaluand @field jump destination
    INNER_JUMP,            // Unconditional jump

    MOTION__GLIDEITERATION,

    MOTION_MOVESTEPS,
    MOTION_TURNRIGHT,
    MOTION_GOTO,
    MOTION_GOTO_MENU,
    MOTION_GOTOXY,
    MOTION_GLIDETO,
    MOTION_GLIDETO_MENU,
    MOTION_GLIDESECSTOXY,
    MOTION_POINTINDIRECTION,
    MOTION_POINTTOWARDS,
    MOTION_POINTTOWARDS_MENU,
    MOTION_CHANGEXBY,
    MOTION_SETX,
    MOTION_CHANGEYBY,
    MOTION_SETY,
    MOTION_IFONEDGEBOUNCE,
    MOTION_SETROTATIONSTYLE,
    MOTION_XPOSITION,
    MOTION_YPOSITION,
    MOTION_DIRECTION,

    LOOKS_SAY,
    LOOKS_THINKFORSECS,
    LOOKS_THINK,
    LOOKS_SWITCHCOSTUMETO,
    LOOKS_COSTUME,
    LOOKS_NEXTCOSTUME,
    LOOKS_SWITCHBACKDROPTO,
    LOOKS_BACKDROPS,
    LOOKS_NEXTBACKDROP,
    LOOKS_CHANGESIZEBY,
    LOOKS_SETSIZETO,
    LOOKS_CHANGEEFFECTBY,
    LOOKS_SETEFFECTTO,
    LOOKS_CLEARGRAPHICEFFECTS,
    LOOKS_SHOW,
    LOOKS_HIDE,
    LOOKS_GOTOFRONTBACK,
    LOOKS_GOFORWARDBACKWARDLAYERS,
    LOOKS_COSTUMENUMBERNAME,
    LOOKS_BACKDROPNUMBERNAME,
    LOOKS_SIZE,

    INNER__WAITITERATION,

    INNER_DEBUGSTATEMENT,
};
